### ISSUE TITLE
"Searching account last rank" infinite loop

### ISSUE THREAD

**Issue by 0BuRner** [akiver/CSGO-Demos-Manager#49]
I updated sources and compiled the project first, then analyzed some games and after analysis finished, "Searching account's last rank" appear on top and never hide. Even the "Stop" button doesn't work...

**Comment by akiver** [comment]
This commit 1d740f48937f26621b68d9f45877278fdb109478 should fix this problem.

**Comment by 0BuRner** [comment]
Not fixed.
Still not able to stop the rank search and it never ends...

**Comment by Calak** [comment]
Which types and how many demos?
What's your computer configuration? Giving a more explicit context can lead to an easier fix of your bug.

**Comment by Calak** [comment]
Which types and how many demos?
What's your computer configuration? Giving a more explicit context can lead to an easier fix of your bug.
