### ISSUE TITLE
Error while try to get suspects information

### ISSUE THREAD

**Issue by zingz0r** [akiver/CSGO-Demos-Manager#65]
Reproduce:
Right click on demo -> Add players to suspects list -> Error while try to get suspects information

**Comment by akiver** [comment]
Could you send me the errors.log file plz?
This issue seems to be related to the Steam API or your connection.

**Comment by zingz0r** [comment]
Sure, but could you tell me please where is it located, because if I go to [Settings] -> [Errors log file] it only  opens the 'My Computer'.

**Comment by akiver** [comment]
@zingz0r It's located in the app installation folder.

**Comment by zingz0r** [comment]
Sorry but there's no error.log on my pc.
What i tried:
 - checked csgo demos dir. (no error.log)
 - reinstalled app and checked dir. (no error.log)
 - created an error.log, restarted app and reproduced the steps (#65) (error.log empty)

**Comment by akiver** [comment]
Should be fixed with the version 2.5.0.

**Comment by Cylo0n** [comment]
Sorry. Still getting this error while adding to suspect list.

**Comment by zingz0r** [comment]
im still getting it too

**Comment by Cylo0n** [comment]
I justed checked it with new Version but the problem isn't solved yet. Starting Application i am getting the error.

**Comment by akiver** [comment]
Still no errors.log? You can navigate to it from settings.

**Comment by Cylo0n** [comment]
No there's no error log in application folder. Or in other words i can't find any log file.
